#!/usr/bin/env python3
"""
DUF Converter Script - Convert DUF files and publish to EVO workspace.
"""

import os
import sys
import argparse
import pprint
from dotenv import load_dotenv

from evo.data_converters.duf.importer import convert_duf
from evo.data_converters.common.evo_client import EvoWorkspaceMetadata


def main():
    """Main function to handle command line execution."""
    # Load environment variables from .env file
    load_dotenv()
    
    parser = argparse.ArgumentParser(description='Convert DUF files and publish to EVO workspace')
    parser.add_argument('--duf-file', '-f', 
                       help='Path to the DUF file to convert',
                       default=None)
    parser.add_argument('--epsg-code', '-e', 
                       type=int,
                       help='EPSG code for coordinate system',
                       default=32650)
    parser.add_argument('--upload-path', '-p',
                       help='Upload path in the workspace',
                       default='notebook1')
    parser.add_argument('--combine-layers', '-c',
                       action='store_true',
                       help='Combine objects in layers',
                       default=True)
    
    args = parser.parse_args()
    
    # Set up credentials from environment variables
    org_id = os.getenv('EVO_ORG_ID')
    workspace_id = os.getenv('EVO_WORKSPACE_ID')
    client_id = os.getenv('EVO_CLIENT_ID')
    client_secret = os.getenv('EVO_CLIENT_SECRET')
    hub_url = os.getenv('EVO_HUB_URL')
    user_id = os.getenv('EVO_USER_AGENT')
    
    # Validate required environment variables
    required_vars = {
        'EVO_ORG_ID': org_id,
        'EVO_WORKSPACE_ID': workspace_id,
        'EVO_CLIENT_ID': client_id,
        'EVO_CLIENT_SECRET': client_secret,
        'EVO_HUB_URL': hub_url,
        'EVO_USER_AGENT': user_id
    }
    
    missing_vars = [var for var, value in required_vars.items() if not value]
    if missing_vars:
        print(f"Error: Missing required environment variables: {', '.join(missing_vars)}")
        print("Please create a .env file with the following variables:")
        print("  EVO_ORG_ID=<your-org-id>")
        print("  EVO_WORKSPACE_ID=<your-workspace-id>")
        print("  EVO_CLIENT_ID=<your-client-id>")
        print("  EVO_CLIENT_SECRET=<your-client-secret>")
        print("  EVO_HUB_URL=<your-hub-url>")
        print("  EVO_USER_AGENT=<your-user-agent>")
        sys.exit(1)
    
    creds = EvoWorkspaceMetadata(
        org_id=org_id,
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        hub_url=hub_url,
        user_id=user_id,
    )
    
    # Determine DUF file path
    if args.duf_file:
        duf_file = args.duf_file
    else:
        # Use default file
        duf_file = os.path.join(os.getcwd(), "data", "input", "Marlin Stopes.duf")
    
    # Check if file exists
    if not os.path.exists(duf_file):
        print(f"Error: DUF file not found: {duf_file}")
        sys.exit(1)
    
    print(f"Converting DUF file: {duf_file}")
    print(f"EPSG Code: {args.epsg_code}")
    print(f"Upload Path: {args.upload_path}")
    print(f"Combine Layers: {args.combine_layers}")
    print("-" * 50)
    
    # Set up tags
    tags = {"Source": "Auto-generated by DUF converter script"}
    
    try:
        # Call convert_duf function
        objects_metadata = convert_duf(
            filepath=duf_file,
            epsg_code=args.epsg_code,
            evo_workspace_metadata=creds,
            tags=tags,
            upload_path=None,
            combine_objects_in_layers=True,
            overwrite_existing_objects=True,
        )
        
        print()
        print("These objects have now been published:")
        print("-" * 50)
        
        for metadata in objects_metadata:
            pprint.pp(metadata, indent=4)
            
        print(f"\nSuccessfully converted and published {len(objects_metadata)} objects!")
        
    except Exception as e:
        print(f"Error during conversion: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
